# Generated by Django 6.0.1 on 2026-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminded_5min',
            field=models.BooleanField(default=False),
        ),
    ]
