# Generated by Django 6.0.1 on 2026-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_event_reminded_5min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminded_5min',
        ),
        migrations.AddField(
            model_name='event',
            name='reminded_5min_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
